/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        income: { DEFAULT: "hsl(var(--income))", foreground: "hsl(var(--income-foreground))" },
        expense: { DEFAULT: "hsl(var(--expense))", foreground: "hsl(var(--expense-foreground))" },
        profit: { DEFAULT: "hsl(var(--profit))", foreground: "hsl(var(--profit-foreground))" },
      },
      borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)" },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { from: { opacity: "0", transform: "translateY(10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-in": { from: { transform: "translateX(-100%)" }, to: { transform: "translateX(0)" } },
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
        shimmer: "shimmer 2s linear infinite",
      },
      backgroundImage: {
        "gradient-sidebar": "linear-gradient(180deg, hsl(var(--sidebar-from)) 0%, hsl(var(--sidebar-to)) 100%)",
        "gradient-card-income": "linear-gradient(135deg, hsl(142 71% 45%) 0%, hsl(158 64% 52%) 100%)",
        "gradient-card-expense": "linear-gradient(135deg, hsl(0 84% 60%) 0%, hsl(15 75% 55%) 100%)",
        "gradient-card-profit": "linear-gradient(135deg, hsl(217 91% 60%) 0%, hsl(199 89% 48%) 100%)",
        "gradient-card-total": "linear-gradient(135deg, hsl(262 83% 58%) 0%, hsl(292 91% 66%) 100%)",
        shimmer: "linear-gradient(90deg, transparent 0%, hsl(var(--muted)) 50%, transparent 100%)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
